name: portuguese_dictionary
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/data/definitions.json