name: Flutter CI/CD

on: [push, pull_request]

jobs: 
  build: 
    # Setting up the environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v1.4.0
    
    - run: flutter pub get
    
    - run: flutter analyze
    
    # Run our tests
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/lcov.info
